<?php
$fd = 5;
$arrayArticles = [
    [
        "path" => "/articles/",
        "name" => "main",
        "url" => "/articles/articles/index.php",
    ],
    [
        "path" => "/articles/diksha_kak_ona_est",
        "name" => "diksha_kak_ona_est",
        "second_name" => "ДИКША — КАК ОНА ЕСТЬ !",
        "url" => "/articles/articles/diksha_kak_ona_est.php",
        "img_url" => "/media/img/articles/article1.jpg",
        "views" => $arrayViews[$arrayArticles[1]["name"]],
        "id" => 1,
    ],
    [
        "path" => "/articles/istinnyi_guru",
        "name" => "istinnyi_guru",
        "second_name" => "КТО ИСТИННЫЙ ГУРУ ?",
        "url" => "/articles/articles/istinnyi_guru.php",
        "img_url" => "/media/img/articles/article2.jpg",
        "views" => $arrayViews[$arrayArticles[2]["name"]],
        "id" => 2,
    ],
    [
        "path" => "/articles/pyat_samskar_v_sisteme_pancharatrika_vidhi",
        "name" => "pyat_samskar_v_sisteme_pancharatrika_vidhi",
        "second_name" => "Пять самскар в системе панчаратрика_видхи",
        "url" => "/articles/articles/pyat_samskar_v_sisteme_pancharatrika_vidhi.php",
        "img_url" => "/media/img/articles/article3.jpg",
        "views" => $arrayViews[$arrayArticles[3]["name"]],
        "id" => 3,
    ],
    [
        "path" => "/articles/pro_tilaku_i_kak_ee_nanosit",
        "name" => "pro_tilaku_i_kak_ee_nanosit",
        "second_name" => "Про ТИЛАКУ и как её наносить",
        "url" => "/articles/articles/pro_tilaku_i_kak_ee_nanosit.php",
        "img_url" => "/media/img/articles/article4.jpg",
        "views" => $arrayViews[$arrayArticles[4]["name"]],
        "id" => 4,
    ],
    [
        "path" => "/articles/shrimati_tulasi_devi",
        "name" => "shrimati_tulasi_devi",
        "second_name" => "Шримати Туласи Деви",
        "url" => "/articles/articles/shrimati_tulasi_devi.php",
        "img_url" => "/media/img/articles/article5.jpg",
        "views" => $arrayViews[$arrayArticles[5]["name"]],
        "id" => 5,
    ],
    [
        "path" => "/articles/vneshnii_vid_i_odezhda_vaishnava",
        "name" => "vneshnii_vid_i_odezhda_vaishnava",
        "second_name" => "Внешний вид и одежда Вайшнава",
        "url" => "/articles/articles/vneshnii_vid_i_odezhda_vaishnava.php",
        "img_url" => "/media/img/articles/article6.jpg",
        "views" => $arrayViews[$arrayArticles[6]["name"]],
        "id" => 6,
    ],
    [
        "path" => "/articles/mayapurskii_kalendar_dlya_vsego_iskcon",
        "name" => "mayapurskii_kalendar_dlya_vsego_iskcon",
        "second_name" => "Маяпурский календарь для всего ISKCON",
        "url" => "/articles/articles/mayapurskii_kalendar_dlya_vsego_iskcon.php",
        "img_url" => "/media/img/articles/article7.jpg",
        "views" => $arrayViews[$arrayArticles[7]["name"]],
        "id" => 7,
    ],
    [
        "path" => "/articles/shikha_i_ee_znachenie",
        "name" => "shikha_i_ee_znachenie",
        "second_name" => "Шикха и её значение",
        "url" => "/articles/articles/shikha_i_ee_znachenie.php",
        "img_url" => "/media/img/articles/article8.jpg",
        "views" => $arrayViews[$arrayArticles[8]["name"]],
        "id" => 8,
    ],
    [
        "path" => "/articles/nektarnye_poucheniya_shri_chaitani",
        "name" => "nektarnye_poucheniya_shri_chaitani",
        "second_name" => "Нектарные поучения Шри Чайтаньи",
        "url" => "/articles/articles/nektarnye_poucheniya_shri_chaitani.php",
        "img_url" => "/media/img/articles/article9.jpg",
        "views" => $arrayViews[$arrayArticles[9]["name"]],
        "id" => 9,
    ],
    [
        "path" => "/articles/voprosy_otvety_o_tulasi_devi_iz_gazety_gaudiya_30_h_godov",
        "name" => "voprosy_otvety_o_tulasi_devi_iz_gazety_gaudiya_30_h_godov",
        "second_name" => "Вопросы_ответы о Туласи Деви (из газеты «Гаудия» 30_х годов)",
        "url" => "/articles/articles/voprosy_otvety_o_tulasi_devi_iz_gazety_gaudiya_30_h_godov.php",
        "img_url" => "/media/img/articles/article10.jpg",
        "views" => $arrayViews[$arrayArticles[10]["name"]],
        "id" => 10,
    ],
];
